protection:
  branches:
    - name: mainline
      restrictions:
        users: []
        teams: []
      required_status_checks:
        strict: true
        contexts:
          - validate
          - build-and-test
      enforce_admins: true
      required_pull_request_reviews:
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        required_approving_review_count: 1
      required_linear_history: true
      allow_force_pushes: false
      allow_deletions: false 