version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: <TASK_DEFINITION>
        LoadBalancerInfo:
          ContainerName: "smart-dine-dev-backend"
          ContainerPort: 80
        PlatformVersion: "LATEST"
        NetworkConfiguration:
          AwsvpcConfiguration:
            Subnets: ["subnet-08ed930771bcdbcaf", "subnet-0701cc5a71761e9f5"]
            SecurityGroups: ["sg-058d3b9f05fa6903e"]
            AssignPublicIp: "DISABLED" 