version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - echo Checking deployment files...
      - ls -la
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - cd backend
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - cd ..
      - echo Creating build artifacts directory...
      - mkdir -p build_artifacts
      # Create the image definitions file
      - printf '[{"name":"smart-dine-dev-backend","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > build_artifacts/imageDefinitions.json
      # Copy deployment files
      - cp appspec.yaml build_artifacts/
      - cp taskdef.json build_artifacts/
      # Update task definition with the new image
      - sed -i.bak -e "s|<IMAGE_NAME>|$REPOSITORY_URI:$IMAGE_TAG|g" build_artifacts/taskdef.json
      - cat build_artifacts/taskdef.json

artifacts:
  files:
    - imageDefinitions.json
    - appspec.yaml
    - taskdef.json
  base-directory: build_artifacts 