version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing dependencies...
      - apt-get update && apt-get install -y jq
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - FULL_IMAGE_URI=$REPOSITORY_URI:$IMAGE_TAG
      - echo Checking deployment files...
      - ls -la
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - cd backend
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image detail file...
      - cd ..
      - echo Creating build artifacts directory...
      - mkdir -p build_artifacts
      # Create the image detail file for blue/green deployment
      - printf '{"ImageURI":"%s"}' $FULL_IMAGE_URI > build_artifacts/imageDetail.json
      # Copy deployment files
      - cp appspec.yaml build_artifacts/
      - cp taskdef.json build_artifacts/
      # Do not modify taskdef.json - let CodeDeploy handle the substitution
      - cp taskdef.json build_artifacts/
      - cat build_artifacts/imageDetail.json

artifacts:
  files:
    - imageDetail.json
    - appspec.yaml
    - taskdef.json
  base-directory: build_artifacts 