version: '3.8'

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "8000:8000"
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - REDIS_HOST=redis
    depends_on:
      - redis
      - auth-service
      - restaurant-service
      - preference-service
      - review-service

  auth-service:
    build: ./backend
    ports:
      - "8001:8001"
    environment:
      - SERVICE_NAME=auth-service
      - PORT=8001
    depends_on:
      - postgres

  restaurant-service:
    build: ./backend
    ports:
      - "8002:8002"
    environment:
      - SERVICE_NAME=restaurant-service
      - PORT=8002
    depends_on:
      - postgres

  preference-service:
    build: ./backend
    ports:
      - "8003:8003"
    environment:
      - SERVICE_NAME=preference-service
      - PORT=8003
    depends_on:
      - postgres

  review-service:
    build: ./backend
    ports:
      - "8004:8004"
    environment:
      - SERVICE_NAME=review-service
      - PORT=8004
    depends_on:
      - postgres

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=smartdine
      - POSTGRES_PASSWORD=smartdine
      - POSTGRES_DB=smartdine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  redis_data: 